Lesson 1
foxygen98/2019-2-Track-Frontend-O-Anoshchenko pull request #1
Opened 2019-10-05 14:33 UTC by foxygen98

# Домашнее задание № 1

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Создан проект
* Написаны 3 функции: convertBytesToHuman, correctSentence, nonUniqueElements
* Написаны тесты для функции convertBytesToHuman

2019-10-06 12:11 UTC, chexex requested changes
Подключить репозиторий к travis-ci.org

2019-10-06 12:11 UTC, chexex commented on package.json
> +  "homepage": "https://your_gh_login.github.io/your_repo_name",
```suggestion
  "homepage": "https://foxygen98.github.io/2019-2-Track-Frontend-O-Anoshchenko/",
```

2019-10-06 14:18 UTC, foxygen98 commented on package.json
> +  "homepage": "https://your_gh_login.github.io/your_repo_name",
Подключила

2019-10-06 18:15 UTC, chexex commented
https://travis-ci.org – здесь репозиторий добавлен?

2019-10-07 06:21 UTC, chexex approved these changes
Функции +
Тесты +
Сборка +

Спасибо за работу,
12 баллов

2019-10-07 06:21 UTC, merged