HW3
foxygen98/2019-2-Track-Frontend-O-Anoshchenko pull request #11
Opened 2020-04-10 18:16 UTC by foxygen98

# Домашнее задание №3

Прошу @martinkomitsky, @chexex проверить его.

Что было сделано:
* Выполнена команда npm run eject
* Реализована клавиатура смайлов

2020-04-10 20:50 UTC, martinkomitsky commented on config/webpack.config.js
> +      {
это надо поместить в другое место, так как ты используешь `.module.css`. Спрайты не собираются

2020-04-10 20:51 UTC, martinkomitsky requested changes
1. Спрайты не собираются, они все как отдельные файлы.
2. При попытке отправить емоджи, получается ошибка
![image](https://user-images.githubusercontent.com/14847018/79022255-3009bc80-7b86-11ea-870f-79879f720d53.png)

2020-04-11 19:05 UTC, foxygen98 commented
Отправку смайлов исправила.
Смайлик kiss теперь тоже собирается в спрайт.

2020-04-15 07:24 UTC, martinkomitsky commented on src/components/EmojiKeyboard.js
> +const emojiKeys = [
вот этот массив можно сделать экспортируемым

2020-04-15 07:25 UTC, martinkomitsky commented on src/components/Messages.js
> +const emojiKeys = [
чтобы здесь его не копипастить, а просто импортировать из того модуля

2020-04-15 07:25 UTC, martinkomitsky approved these changes
Исправить замечание в следующем ДЗ

6

2020-04-15 07:25 UTC, merged