Typescript 2
foxygen98/2019-2-Track-Frontend-O-Anoshchenko pull request #13
Opened 2020-04-27 19:33 UTC by foxygen98

# Домашнее задание №7

Прошу @martinkomitsky или @chexex проверить его.

Что было сделано:
* Создан новый проект
* Подключена библиотека d3 с тайпингами
* Разработан модуль с визуализацией

2020-04-28 17:28 UTC, chexex requested changes
Необходимо довезти типы (xAxis)

https://www.npmjs.com/package/@types/d3-selection

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/d3-selection

2020-04-28 17:28 UTC, chexex commented on .travis.yml
> +#  - npm run lint
Почему без линтера?

2020-04-28 17:28 UTC, chexex commented on ts2/.env
> +SKIP_PREFLIGHT_CHECK=true
какой-то префлайтчек лишний

2020-04-28 17:28 UTC, chexex commented on ts2/src/App.test.tsx
> +});
Есть тест – хорошо. Но почему выключен npm test из ci?

2020-04-28 17:28 UTC, chexex commented on ts2/src/App.tsx
> +      if (i.Math !== undefined) {
```suggestion
      if (i.Math) {
```

2020-04-28 17:28 UTC, chexex commented on ts2/src/App.tsx
> +        i.Math = `${Math.floor(+i.Math/2) * 2}`
Почему `Math.floor`, не `Math.round` или `Math.ceil`?

2020-04-28 17:28 UTC, chexex commented on ts2/src/App.tsx
> +    Object.entries(data.math).forEach(([key, value]) => resultData.math.push({name: key, value: value}))
типов не хватает

2020-04-28 17:28 UTC, chexex commented on ts2/src/App.tsx
> +  const [data, setData] = useState({math: []} as T.IProps)
тайпинг для `data`, `setData`

2020-04-28 17:28 UTC, chexex commented on ts2/src/MyD3Component.tsx
> +            const xAxis = (g: any) => g
`g: any`, кажется у аргумента `g` должен быть специальный тип :)

2020-05-03 21:41 UTC, foxygen98 commented
* Подключила линтер и тесты
* Убрала один лишний .env
* Заменила Math.floor на Math.ceil :)
* Добавила типы

2020-05-07 07:21 UTC, chexex approved these changes
12 баллов

2020-05-07 07:21 UTC, merged