Lesson 2
foxygen98/2019-2-Track-Frontend-O-Anoshchenko pull request #2
Opened 2019-10-17 09:40 UTC by foxygen98

# Домашнее задание №2

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
*  Стилизовала форму отправки сообщений в соответствии с макетом
* Реализовала сохранение сообщений в localStorage
* Добавила линтер на проект и исправила ошибки

2019-10-17 10:43 UTC, priver requested changes

2019-10-17 10:43 UTC, priver commented on web-components/src/components/MessageForm.js
> +    const window = document.createElement('div');
нужно сделать отдельный компонент для сообщения

2019-10-17 12:02 UTC, foxygen98 commented on web-components/src/components/MessageForm.js
> +    const window = document.createElement('div');
> нужно сделать отдельный компонент для сообщения

Я правильно поняла, что нужно в папке components создать компонент message?

2019-10-18 09:58 UTC, priver commented on web-components/src/components/MessageForm.js
> +    const window = document.createElement('div');
да, и создавать его через `document.createElement()`, передавая значения полей в качестве атрибутов

2019-10-19 03:34 UTC, foxygen98 commented
> # Домашнее задание №2
> Прошу @martinkomitsky, @chexex или @priver проверить его.
> 
> Что было сделано:
> 
> * Стилизовала форму отправки сообщений в соответствии с макетом
> * Реализовала сохранение сообщений в localStorage
> * Добавила линтер на проект и исправила ошибки

2019-10-19 03:48 UTC, foxygen98 commented on web-components/src/components/MessageForm.js
> +    const window = document.createElement('div');
Сделала
Теперь длинные сообщения куда-то влево едут, не могу понять почему(
Помогите, пожалуйста

2019-10-19 08:15 UTC, foxygen98 commented on web-components/src/components/MessageForm.js
> +    const window = document.createElement('div');
Всё, окна с сообщениями поправила, сейчас намного лучше

2019-10-21 09:42 UTC, priver approved these changes
Отлично, 10 баллов (-2 за сдачу после 14 октября)

2019-10-21 09:42 UTC, merged