Lesson 3
foxygen98/2019-2-Track-Frontend-O-Anoshchenko pull request #3
Opened 2019-10-26 15:51 UTC by foxygen98

# Домашнее задание №3

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Шапка для окна списка чатов
* Кнопка создать чат

Всё еще не получается реализовать переход со списка чатов на конкретный чат. Пробую так, как объяснили на семинаре, но что-то не выходит. На данный момент пытаюсь связать CreateChat.js и MessageForm.js. Не могли бы вы подсказать, где я ошибаюсь?

2019-10-27 11:23 UTC, martinkomitsky requested changes
Код, вроде бы, ничего, но сборка не прошла, к сожалению :(
Нужно выполнить требования линтера (npm run test) и запушить снова

2019-10-27 16:25 UTC, foxygen98 commented
Всё готово)

2019-10-28 05:35 UTC, martinkomitsky commented
> Всё готово)

Осталась еще одна проблема :(
`Skipping a deployment with the pages provider because this branch is not permitted: lesson_3`

Знаешь, как исправить?

2019-10-28 19:30 UTC, foxygen98 commented
Исправила)

2019-10-29 04:32 UTC, martinkomitsky approved these changes
Теперь все ОК, спасибо!

Но, к сожалению, за то, что срок прошел уже как неделю - 6 :(
Рекомендую не расстраиваться, а сделать халявную 4 дз и приступать к реакту!

2019-10-29 04:32 UTC, merged